mt6768-common: Don't build FMRadio
I'm done with FMRadio, fuck off libfmjni.

error: packages/apps/FMRadio/Android.bp:17:1: FMRadio depends on undefined module libfmjni.
Module FMRadio is defined in namespace . which can read these 12 namespaces: [. . vendor/gms/common vendor/xiaomi/merlinx hardware/xiaomi vendor/xiaomi/mt6768-common device/xiaomi/mt6768-common hardware/mediatek hardware/google/pixel hardware/google/interfaces device/xiaomi/merlinx hardware/mediatek/libmtkperf_client]
Module libfmjni can be found in these namespaces: [packages/apps/FMRadio/jni/fmr]
Or did you mean [libgljni libjni librsjni]?
fatal errors encountered
12:22:20 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

Signed-off-by: Ksawlii <ksawery.blaszczak@proton.me>