mt6768-common: manifest: Revert to target-level 5
Why? 6 is for 4.19+ and mt6768 (merlinx, lancelot) have 4.14. Anyways
here is the error

ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No kernel entry found for kernel version 4.14 at kernel FCM version 6. The following kernel requirements are checked:
  Minimum LTS: 4.19.191, kernel FCM version: 6
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 4.19.191, kernel FCM version: 6, with conditionals
  Minimum LTS: 5.4.86, kernel FCM version: 6
  (there was more up to 6.6)

This reverts commit 2548da2dafb3bdae7931722b2d73ad965d207e62.

Signed-off-by: Ksawlii <ksawery.blaszczak@proton.me>